vim9script

# CORE SETTINGS
set hlsearch incsearch ignorecase smartcase
set wildignore+=*.exe,*.dll,*.pdb,*.class,*.o,*.d
set wildignore+=*/.git/*,*/node_modules/*,*/dist/*,*/build/*,*/target/*
set wildignorecase
set grepformat=%f:%l:%m
set splitbelow splitright
set shortmess+=IcC
set ttimeout ttimeoutlen=25
set updatetime=300
set hidden confirm lazyredraw
set tabstop=4 shiftwidth=4 expandtab
set smartindent
set fileformats=unix,dos
set nrformats=bin,hex,unsigned
set virtualedit=block nostartofline
set tags=./tags;,tags;
filetype plugin indent on

# PERSISTENT UNDO
if !isdirectory($HOME .. '/.vim/undo')
    mkdir($HOME .. '/.vim/undo', 'p', 0o700)
endif
set undofile undodir=~/.vim/undo

# WRAPPING & SCROLLING
set nowrap
set linebreak
set display=lastline
set scrolloff=4
set sidescroll=1 sidescrolloff=5

# UI & COLORS
if has('termguicolors')
    set termguicolors
endif
syntax on
try
    colorscheme dot
catch
    colorscheme habamax
endtry
set listchars=tab:·\ ,trail:·,nbsp:␣
set laststatus=2
set nojoinspaces

# COMPLETION
set completeopt=menu,popup
set complete=.,w,b,u,t

# STATUSLINE
augroup VrcStatusline
    autocmd!
    autocmd DirChanged * g:cwd_tail = fnamemodify(getcwd(), ':t')
augroup END
g:cwd_tail = fnamemodify(getcwd(), ':t')
set statusline=%#StatusLine#\ %f\ %m%r%=%{g:cwd_tail}\ %L\ %l:%c\ 

# KEYMAPS
g:mapleader = ' '

nnoremap <leader>e          :e<Space>
nnoremap <leader>d          :cd<Space>
nnoremap <leader>g          :grep<Space>
nnoremap <silent> <leader>q :copen<CR>
nnoremap <silent> <leader>n :cnext<CR>
nnoremap <silent> <leader>p :cprev<CR>
nnoremap <silent> <leader>t :Sex<CR>
nnoremap <silent> <Tab>     :bnext<CR>
nnoremap <silent> <S-Tab>   :bprevious<CR>
nnoremap <silent> <leader>m :make<CR>
nnoremap <silent> <leader>/ :nohlsearch<CR>

# FUZZY FINDER
if executable('fzf')
    if executable('fd')
        $FZF_DEFAULT_COMMAND = 'fd . --exclude build --exclude .git'
    else
        $FZF_DEFAULT_COMMAND = 'find . \( -path "*/build/*" -o -path "*/.git/*" \) -prune -o -type f -print'
    endif
    nnoremap <leader>f :FZF<CR>
else
    set path=.,**
    nnoremap <leader>f :find<Space>
endif

# SEARCH / GREP TOOLS
if executable('rg')
    &grepprg = 'rg --vimgrep --no-heading --smart-case'
    &grepformat = '%f:%l:%c:%m,%f:%l:%m'
elseif executable('grep')
    &grepprg = 'grep -n -R -I -E --exclude-dir=.git'
    &grepformat = '%f:%l:%m'
endif

# DEBUGGER
def LoadTermdebug(args: string)
    packadd termdebug
    execute 'Termdebug ' .. args
enddef
command! -nargs=* -complete=file Debug LoadTermdebug(<q-args>)

# CUSTOM FUNCTIONS
def RunFZF()
    if !has('terminal')
        echom 'fzf not available: missing +terminal'
        return
    endif
    var tmpfile = tempname()
    var cmd = 'fzf > ' .. tmpfile
    term_start(['sh', '-c', cmd], {
        term_finish: 'close',
        exit_cb: (_, status) => {
            if status == 0 && filereadable(tmpfile)
                var lines = readfile(tmpfile)
                if !empty(lines) && !empty(lines[0])
                    execute 'edit ' .. fnameescape(lines[0])
                endif
            endif
            if filereadable(tmpfile)
                delete(tmpfile)
            endif
        }
    })
enddef
command! -nargs=0 FZF RunFZF()

def HexToggle()
    if &l:binary && &l:filetype ==# 'xxd'
        silent :%!xxd -r
        setlocal filetype=
    else
        if &modified
            echohl WarningMsg | echom 'HexToggle: save changes first' | echohl None
            return
        endif
        setlocal binary
        silent edit
        silent :%!xxd -g1
        setlocal filetype=xxd
    endif
enddef
command! -nargs=0 HexToggle HexToggle()
