#!/bin/sh
# warmer colors from 18:00 to 06:00
exec 2>&1
pkill -u "$(id -u)" -x wlsunset
# for the nightlight icon in the bar
echo $$ >"${XDG_RUNTIME_DIR:-/tmp}/nightlight.pid"
exec wlsunset -t 4000 -T 4001 -S 06:00 -s 18:00
