#!/bin/sh
# the sound server, wireplumber and pipewire-pulse connect to it
exec 2>&1
# no X11 bell module, it would read ~/.Xauthority
unset DISPLAY XAUTHORITY
pkill -u "$(id -u)" -x pipewire
exec pipewire
