# COMPILE FLAGS
COMMON_FLAGS="-march=native -O2 -pipe -fno-plt
  -fstack-protector-strong \
  -fstack-clash-protection \
  -fno-semantic-interposition \
  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

LDFLAGS="-Wl,-O1 -Wl,--as-needed \
  -Wl,-z,relro,-z,now \
  -Wl,-z,noexecstack \
  -Wl,-z,pack-relative-relocs \
  -Wl,--hash-style=both"
RUSTFLAGS="-C target-cpu=native -C opt-level=2"

# BUILD
MAKEOPTS="-j11 -l9"
EMERGE_DEFAULT_OPTS="--keep-going --with-bdeps=y --verbose-conflicts \
  --jobs=6 --load-average=9 \
  --complete-graph=y --backtrack=50"

# FEATURES
FEATURES="
  ccache
  clean-logs
  fail-clean
  parallel-fetch
  parallel-install
  usersandbox
  pid-sandbox
  ipc-sandbox
  userpriv
"
PORTAGE_TMPDIR="/var/tmp/portage"

# LOGS
PORTAGE_LOGDIR="/var/log/portage"
PORTAGE_ELOG_CLASSES="log warn error"
PORTAGE_ELOG_SYSTEM="save"

# USE FLAGS
USE="
  man X wayland vulkan opengl
  pipewire pipewire-pulse
  screencast dbus elogind
  policykit
  gbm drm gles2
  udev xdg ime
  -pulseaudio-daemon 
  -systemd -bluetooth
  -kde -gnome
  -smartcard -ibm -ieee1394 -ipod
  -clamav -cups -test
"

# HARDWARE
#CPU_FLAGS_X86="aes avx avx2 avx512_bf16 avx512_bitalg avx512_vbmi2 avx512_vnni avx512_vpopcntdq avx512bw avx512cd avx512dq avx512f avx512ifma avx512vbmi avx512vl bmi1 bmi2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 vpclmulqdq"
#LLVM_TARGETS="AMDGPU x86"
#VIDEO_CARDS="amdgpu radeonsi"
INPUT_DEVICES="libinput"
ABI_X86="64"

# BOOT & LOCAL
LC_MESSAGES=C.UTF-8
GRUB_PLATFORMS="efi-64"
