install rds /bin/false
install tipc /bin/false
install atm /bin/false
install n_hdlc /bin/false
install firewire-core /bin/false
install firewire-ohci /bin/false
install firewire-sbp2 /bin/false
install firewire-net /bin/false
install floppy /bin/false
install cramfs /bin/false
install hfs /bin/false
install befs /bin/false
install qnx6 /bin/false
install adfs /bin/false
install ufs /bin/false
