install rds /bin/false
install tipc /bin/false
install atm /bin/false
install n_hdlc /bin/false
install n_gsm /bin/false
install sctp /bin/false
install appletalk /bin/false
install psnap /bin/false
install llc2 /bin/false
install phonet /bin/false
install ax25 /bin/false
install netrom /bin/false
install rose /bin/false
install firewire-core /bin/false
install firewire-ohci /bin/false
install firewire-sbp2 /bin/false
install firewire-net /bin/false
install floppy /bin/false
install cramfs /bin/false
install hfs /bin/false
install befs /bin/false
install qnx6 /bin/false
install adfs /bin/false
install ufs /bin/false
install hpfs /bin/false
install jfs /bin/false
install gfs2 /bin/false
install ocfs2 /bin/false
