flush ruleset

table inet filter {
    chain input {
        type filter hook input priority filter;
        policy drop;

        iif lo accept

        ct state invalid drop
        ct state established,related accept

        ip protocol icmp limit rate 10/second accept
        ip6 nexthdr icmpv6 accept

        udp sport 67 udp dport 68 accept

        limit rate 5/minute log prefix "nft-input-drop: " counter drop
        counter drop
    }

    chain forward {
        type filter hook forward priority filter;
        policy drop;
    }

    chain output {
        type filter hook output priority filter;
        policy accept;
    }
}
