[main]
time-format=%H:%M
date-format=%A %d %B
# show only the clock when idle, any key brings the form back
idle-hide=true
idle-timeout=10
lock-command=playerctl -a pause
layout=@HOME@/.config/gtklock/layout.ui
