flush ruleset

table inet filter {
    chain input {
        type filter hook input priority filter;
        policy drop;

        iif lo accept

        ct state invalid drop
        ct state established,related accept

        ip protocol icmp limit rate 10/second accept
        icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem } accept
        icmpv6 type echo-request limit rate 10/second accept
        icmpv6 type { nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert } ip6 hoplimit 255 accept
        ip6 saddr fe80::/10 icmpv6 type mld-listener-query accept

        udp sport 67 udp dport 68 accept
        ip6 saddr fe80::/10 udp sport 547 udp dport 546 accept

        limit rate 5/minute log prefix "nft-input-drop: " counter drop
        counter drop
    }

    chain forward {
        type filter hook forward priority filter;
        policy drop;
    }

    chain output {
        type filter hook output priority filter;
        policy accept;
    }
}
