[main]
font=DejaVu Sans Mono:size=11

[colors-dark]
background=000000
foreground=ffffff

# normal
regular0=000000  # black
regular1=ff0000  # red
regular2=00ff00  # green
regular3=ffff00  # yellow
regular4=0000ff  # blue
regular5=ff00ff  # magenta
regular6=00ffff  # cyan
regular7=ffffff  # white

# bright
bright0=555555
bright1=ff5555
bright2=55ff55
bright3=ffff55
bright4=5555ff
bright5=ff55ff
bright6=55ffff
bright7=ffffff

# cursor
cursor=98c379 98c379

# selection
selection-foreground=ffffff
selection-background=4e5579
