[main]
font=DejaVu Sans Mono:size=10

[colors]
background=0a0a0a
foreground=e9e9e9

# normal
regular0=0a0a0a
regular1=cc6666
regular2=8c9a8c
regular3=ffee8f
regular4=708a99
regular5=a6829c
regular6=70a09f
regular7=8a8a8a

# bright
bright0=555555
bright1=d97e7e
bright2=afd7af
bright3=ffe066
bright4=8ab0c6
bright5=c59dc8
bright6=8cc8c7
bright7=ffffff

# cursor
cursor=0a0a0a 9d9d9d

# selection
selection-foreground=0a0a0a
selection-background=ffee8f
